
//user details actions

const DETAILS_PENDING = 'DETAILS_PENDING';
const DETAILS_FULFILLED = 'DETAILS_FULFILLED';
const DETAILS_REJECTED = 'DETAILS_REJECTED';
const USER_POSTS_PENDING = 'USER_POSTS_PENDING';
const USER_POSTS_FULFILLED = 'USER_POSTS_FULFILLED';
const USER_POSTS_REJECTED = 'USER_POSTS_REJECTED';

//user actions

const USER_DATA_PENDING = 'USER_DATA_PENDING';
const USER_DATA_FULFILLED = 'USER_DATA_FULFILLED';
const USER_DATA_REJECTED = 'USER_DATA_REJECTED';
const SEARCH_BY_TEXT = 'SEARCH_BY_TEXT';
const SORT_BY_VALUE = 'SORT_BY_VALUE';

export  {
    DETAILS_PENDING,
    DETAILS_FULFILLED,
    DETAILS_REJECTED,
    USER_POSTS_PENDING,
    USER_POSTS_FULFILLED,
    USER_POSTS_REJECTED,
    USER_DATA_PENDING,
    USER_DATA_FULFILLED,
    USER_DATA_REJECTED,
    SEARCH_BY_TEXT,
    SORT_BY_VALUE,
}